version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip airbnb-lambda-to-sqs.py enrichment-eventbridge.py call-to-s3.py

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://A4-airbnb-lambda-to-sqs/
      - aws s3 cp deployment_package.zip s3://a4-enrichment-eventbridge/
      - aws s3 cp deployment_package.zip s3://a4-call-to-s3/
      - echo "Updating Lambda functions via S3..."
      - aws lambda update-function-code --function-name a4-airbnb-lambda-to-sqs --s3-bucket a4-airbnb-lambda-to-sqs --s3-key deployment_package.zip
      - aws lambda update-function-code --function-name a4-enrichment-eventbridge --s3-bucket a4-enrichment-eventbridge --s3-key deployment_package.zip
      - aws lambda update-function-code --function-name a4-call-to-s3 --s3-bucket a4-call-to-s3 --s3-key deployment_package.zip
      - echo "Deployment complete!"
